name: umami CI

on:
  push:
    branches: [ main ]
  # schedule:
    # - cron: '0 20 * * */1'

jobs:
  deplyUmami:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      # - name: Setup Node.js environment.
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12

      # - name: Clone latest code.
      #   run : |
      #     git clone https://github.com/mikecao/umami.git
      #     rm -rf .git/ .github/
      #     cp -r umami/* ./
      #     ls -al

      # - name: Install dependencies.
      #   run: npm install

      # - name: Build App.
      #   run: npm run build

      # - name: Deploy to hosting.
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: "-rltgoDzvO --delete"
      #     # SOURCE: "docs/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.TARGET}}
      #     EXCLUDE: /node_modules/

      - name: Reload umami service
        uses: appleboy/ssh-action@master
        env:
          PRODUCTION_DIR: ${{ secrets.TARGET }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            echo "I am $PRODUCTION_DIR"
            echo "I am $KEY"
            cd $PRODUCTION_DIR
            ls -al
            # npm install
            # pm2 restart umami