name: umami CI

on:
  push:
    branches: [ main ]
  # schedule:
    # - cron: '0 20 * * */1'

jobs:
  deplyUmami:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment.
        uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - name: Clone latest code.
        run : |
          git clone https://github.com/mikecao/umami.git
          cp .env /umami
          cd umami

      - name: Install dependencies.
        run: npm ci

      - name: Build App.
        run: npm run build

      - name: Stop umami service
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: pm2 stop umami
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to hosting.
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          # SOURCE: "docs/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET}}
          EXCLUDE: /node_modules/,/.git/

      - name: Restart pm2 service
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: pm2 restart umami
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}